### PR TITLE
support pubsub.PubOpts in UpdateRoot

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Review by willscott — APPROVED** [review]

**Comment by mvdan** [comment]
Oops, hadn't noticed CI was red until just now. The build is now fixed.

Unfortunately, TestLatestSyncSuccess seems to now hang - presumably because EnoughPeers(1) never becomes true. I'm not really sure how that is happening. I'm trying to debug a little.

**Review by masih — APPROVED** [review]
My vote is to merge this if it makes the tests more stable despite the hanging test

**Comment by mvdan** [comment]
Well, I certainly can't break master in a reproducible way :)

**Comment by gammazero** [comment]
As documented in [`WithReadiness`](https://pkg.go.dev/github.com/libp2p/go-libp2p-pubsub#WithReadiness), I don't think this is going to work without providing a [`WithDiscover`](https://pkg.go.dev/github.com/libp2p/go-libp2p-pubsub#WithDiscovery) to give the pubsub instance a discovery mechanism.

**Pull request closed without merging**
